from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

import build_seasonal_rowgate_candidate as R
import sea_winds_end_to_end_final as E2E


ROOT = Path(__file__).resolve().parent
WORK = ROOT / "runs" / "v6_pressure_speed"


def sha256(path: Path) -> str | None:
    return R.sha256(path) if path.exists() else None


def main() -> None:
    R.ORIG_BASE_CSV = WORK / "pred_sfc14_selw.csv"
    R.CONFIRMED_BASE_CSV = WORK / "pred_sfc14rg_d146.csv"
    R.OUT_CSV = WORK / "pred_ns_sfc14_rg60_d146.csv"
    R.OUT_ZIP = WORK / "sub_nssfc14rg60.zip"
    R.MANIFEST = WORK / "manifest_ns_sfc14_rg60_d146.json"
    R.TARGETS = (("north_sea", "surface", 14),)
    R.STRONG_WEIGHTS_CURRENT = (None,)
    R.DELTA_THRESHOLDS = (60.0,)
    R.MAX_CHANGED_FRACTION = 0.75
    R.MIN_PROXY_GAIN = 0.1
    R.MAX_INFERENCE_SHIFT_P90 = 65.0

    R.require(R.ORIG_BASE_CSV, "Run .\\run_surface_d14_width_on_selective_center_e2e.ps1 first.")
    R.require(R.CONFIRMED_BASE_CSV, "Run .\\run_sfc14rg_d146_e2e.ps1 first.")
    R.cleanup_outputs()

    orig_pred = R.load_model_centers(R.ORIG_BASE_CSV)
    confirmed_pred = R.load_model_centers(R.CONFIRMED_BASE_CSV)
    proxy_table, selected = R.select_candidates(orig_pred, confirmed_pred)
    if len(selected) != 1:
        raise SystemExit(f"expected one selected row-gate block, got {len(selected)}")
    spec = selected[0]
    if spec.region != "north_sea" or spec.group != "surface" or spec.horizon != 14:
        raise SystemExit(f"unexpected selected target: {spec}")
    if spec.weight_current is not None or abs(spec.delta_threshold - 60.0) > 1e-9:
        raise SystemExit(f"unexpected selected row-gate shape: {spec}")

    orig = R.normalize_base(pd.read_csv(R.ORIG_BASE_CSV, low_memory=False))
    confirmed = R.normalize_base(pd.read_csv(R.CONFIRMED_BASE_CSV, low_memory=False))
    R.assert_same_order(orig, confirmed)
    before = confirmed.copy()
    patched, stability = R.apply_candidates(orig, confirmed, selected)
    final = E2E.validate_final(patched)
    delta = R.validate_delta(before, final, selected)
    if delta["speed_rows_changed"] != 0 or delta["non_target_direction_rows_changed"] != 0:
        raise SystemExit(f"unexpected delta: {delta}")
    E2E.write_zip(final, R.OUT_CSV, R.OUT_ZIP)
    R.write_manifest(
        "submission_written_after_forced_rg60_proxy_and_audit",
        (
            "Forced NS surface d14 direct seasonal row gate at delta<=60 on the promoted "
            "d146+rg45 base. This is a bounded strengthening after rg45 transferred "
            "positively on public feedback."
        ),
        proxy_table,
        selected,
        stability=stability,
        delta=delta,
    )

    manifest = json.loads(R.MANIFEST.read_text(encoding="utf-8"))
    manifest["compliance"]["notes"] = [
        "Confirmed base is the promoted official-data-generated pred_sfc14rg_d146.csv artifact.",
        "Original/source base is pred_sfc14_selw.csv, generated by the official-data NS surface d14 selective-center pipeline.",
        "Proxy selection uses only official 2019-2021 train/reanalysis data and generated predictions.",
        "Final inference seasonal centers use official 2019-2021 train reanalysis, all before 2022 inference windows.",
        "Public leaderboard metrics are used only to choose whether to submit/promote a generated candidate, not as model features or labels.",
    ]
    manifest["public_feedback_basis"] = {
        "current_promoted_base": "sub_sfc14rgd146.zip",
        "current_base_public_score": 1.442113,
        "target_metric": "Dir NS Surface d14",
        "current_metric": 326.4197,
        "leader_reference_metric": 298.76,
        "previous_positive_point": {
            "submission": "sub_sfc14rgd146.zip",
            "shape": "direct seasonal_w21 where original/seasonal disagreement <=45 degrees",
            "public_metric": 326.4197,
        },
        "candidate_shape": {
            "shape": "direct seasonal_w21 where original/seasonal disagreement <=60 degrees",
            "proxy_gain_vs_current": float(spec.proxy_gain),
            "proxy_score": float(spec.proxy_score),
            "changed_fraction": float(spec.changed_fraction),
            "proxy_half_width": float(spec.proxy_half_width),
        },
        "gate": (
            "Promote only if Dir NS Surface d14 improves versus 326.4197 and no accepted "
            "dimension regresses materially."
        ),
    }
    manifest["code_hashes"]["build_ns_sfc14_rg60_d146_candidate.py"] = sha256(Path(__file__).resolve())
    manifest["code_hashes"]["run_ns_sfc14_rg60_d146_e2e.ps1"] = sha256(ROOT / "run_ns_sfc14_rg60_d146_e2e.ps1")
    manifest["code_hashes"]["run_sfc14rg_d146_e2e.ps1"] = sha256(ROOT / "run_sfc14rg_d146_e2e.ps1")
    R.MANIFEST.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"OK forced NS surface d14 rg60 candidate: {R.OUT_ZIP}", flush=True)


if __name__ == "__main__":
    main()
